name = "Revise"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "2.0.0"

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LoweredCodeUtils = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CodeTracking = "0.4"
JuliaInterpreter = "0.2, 0.3"
LoweredCodeUtils = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
EponymTuples = "97e2ac4a-e175-5f49-beb1-4d6866a6cdc3"

[targets]
test = ["Test", "Example", "EponymTuples"]
