name = "ReviseCore"
uuid = "c98ecb09-caa2-44e9-b6bc-86139c117a10"
version = "0.1.0"
authors = ["Tim Holy <tim.holy@gmail.com>, Shuhei Kadowaki <aviatesk@gmail.com>"]

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
LoweredCodeUtils = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
CodeTracking = "2"
JuliaInterpreter = "0.10"
LoweredCodeUtils = "3.4.3"
OrderedCollections = "1"
julia = "1.10"
